export const SET_TOKEN = "SET_TOKEN";
export const CHECK_TOKEN_EXISTS_SUCCESS = "CHECK_TOKEN_EXISTS_SUCCESS";
export const CHECK_TOKEN_EXISTS_FAIL = "CHECK_TOKEN_EXISTS_FAIL";
export const ON_LOGOUT = "ON_LOGOUT"; 
